import type { Metadata } from "next";
import {Roboto} from "next/font/google";
import "./globals.css";
import NavBarr from "@/component/NavBarr";

const font = Roboto({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${font.variable} antialiased min-h-screen`}
      >
          <NavBarr />
        {children}
      </body>
    </html>
  );
}
